### ISSUE TITLE
No such file or directory of dorad

### ISSUE THREAD

**Issue by Bild96** [DoraFactory/doravota#3]
## 💡 copy file directory 
```bash
sudo cp ~/go/bin/dorad /usr/local/bin
```

## 🤳 Screenshots <a name = "screenshots"></a>
![Screenshot from 2023-11-06 00-08-20](https://github.com/DoraFactory/doravota/assets/52472445/61726950-6620-475b-ab9c-523ecef3e33d)

**Comment by VegeBun-csj** [comment]
If you want see more operations about the doravota, you can follow this [toturial](https://df-docs.vercel.app/docs/vota-dev)
